language: node_js
node_js:
  - "6"

before_script:
  - npm install -g --quiet firebase-tools
  - npm run install:all

script:   
  - npm run init
  - npm run build  

after_success:
  - echo 'deploy !!'
