language: node_js
node_js:
- '6'

before_script:
- npm install -g --quiet firebase-tools
- npm run install:all

script:
- npm run init
- npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy:prod
  on:
    branch: master

env:
  global:
  - secure: csJtgSP1VwE13NWBNpLFsX7QaX9CKVEUq+IPUQ8RVB/wVkHu3hxN8swrc+aT6Mv8m6tVF0NEJtWoifDmmFY7D2DemsGBpbUlvAbCzh+rVn8KFOdGpYXbk5JDEFbubpopApdsNg/wYBoAtI868eBsjHkosA5xupBcKxQr80PQnDFlyZajQdYZHv8WP91auOQjjI33YW9uc2uWssD04rOcdgqQlCCB6bhUFxb+gXQSJ049zw3dKgEvQJCmvKtjzv9r52dL3CTiRBQ50b65+3CM1rCKmZy7TbqOJ3xEnmaUWqJfTrpyFT0Av8hMaPZMcck+kWViU1EPTR7NCkVKGHU6mMQfvGuCwihS1F2jjd07dH37zijFScr56LI7LaNuGjifkI3WMpI76FfxCmBpgyV7dIs5dBK09Xkr6aM82+nYnponu5G1axbT6Qo20vTrz7/9Qz4OD1owWtSq3RgKZs6ygSVYDCWe0YcZMVTjW8as3QgAqodOVwg3yp86Iz8BnKtBEuioSLVroyYfC5Rw03BkBYaQbvk96LaSsUHGyrWptECY0M5KOdpKwNPa7R4d8OvZVyfFeAYDeBVE7FMEK2VIz42D+NuBPHhpSdNgGZ/QKZdoHXGmWLtMuy6NoI7Pqcc8QtlWWPfPhgiLhItMaCUY7R18YysQYsYsVzWRHDlryp4=
